### ISSUE TITLE
Instructions: awscli has no installation candidate

### ISSUE THREAD

**Issue by ExplodingLemur** [UnintelligibleMaker/PyTerrainModeler#1]
The package `awscli` is not available in Linux Mint/Ubuntu.  The first line of your instructions direct users to install `awscli` via `apt` which fails as there is no such package.

**Comment by UnintelligibleMaker** [comment]
Looks like my system is older and this has changed.  I've added instructions:
`sudo snap install aws-cli --classic`
That should work on more recent Ubuntu/Mint installs then mine.  Nice catch.

**Comment by UnintelligibleMaker** [comment]
Resolving as I believe the new instructions are accurate.  Feel free to reopen/file a new issue if needed.
